#!/bin/bash

NAME="alpha"                                  			# Name of the application
DJANGODIR=/opt/graphite/webapp/            			    # Django project directory
SOCKFILE=/opt/graphite/run/gunicorn-monitor.sock     	# we will communicte using this unix socket
USER=pi
GROUP=pi                                       			# the user to run as
NUM_WORKERS=3                                     		# how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=graphite.settings            	# which settings file should Django use
DJANGO_WSGI_MODULE=graphite.wsgi                     	# WSGI module name

#echo "Starting $NAME as `pi"

# Activate the virtual environment
cd $DJANGODIR
source /home/pi/.virtualenvs/monitor/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
echo "************-----------> *************"
exec /home/pi/.virtualenvs/monitor/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=info \
  --log-file=-

